### ISSUE TITLE
Problem with coordinate system

### ISSUE THREAD

**Issue by milvus-milvus** [qualisys/paf-opensim-example#3]
Hello,
I have been using Qualisys PAF – OpenSim example for some time to calculate the functional muscle-tendon length of our patients'. Unfortunately, I am encountering the following problems.
The MoCap data I have comes from the Qualisys system, I use the IOR LB model. After uploading the experimental data to OpenSim everything looks fine. However, when I try to correlate them with the Arnoldetal2010_2Legs_Default_v2.1.osim model (with your instructions), my new model is standing sideways (attached picture). After applying inverse kinematics, the model goes sideways. I suspect that the problem lies in the coordinate system because the experimental data "goes" in the opposite direction than the model, but I don't know how to rotate them 180 degrees. Could I ask for help? Thank you in advance. 
![sideways](https://github.com/qualisys/paf-opensim-example/assets/73904094/0eb18ba4-5610-45cf-bd60-e6ae7a7c4817)

**Comment by AndreyAkse** [comment]
Hello Milvus, 

Maybe you could write in more details or provide your example files as well but I was checking Arnoldetal2010_2Legs_Default_v2.1.osim model and it does not use IOR or CAST marker set. Names of the markers are also very different when compared to IOR and CAST. Our Opensim-example contains IOR and CAST marker set models.
It does not support Arnoldetal2010_2Legs_Default_v2.1.osim but you can try to research how to modify that so you can use it. 
<img width="497" alt="image" src="https://github.com/qualisys/paf-opensim-example/assets/120633101/804f3f6d-83fd-4cf9-8997-cad06f7c9d24">

**Comment by AndreyAkse** [comment]
Also, if you go to your project folder and then Templates there is qtm2opensim.py file. If you open it there will be a line (35) where you can rotate marker data. When you process your data in qtm again it will export it with adjusted coordinates.
 # Rotate marker data
    rotate_data_table(markers, [1, 0, 0], -360) # Assumes that z is pointing up vertically in QTM
Just tried to do that and my marker set was also rotated in OpenSim.
I hope it can help.
![image](https://github.com/qualisys/paf-opensim-example/assets/120633101/d0fe1022-acec-4802-94e3-53e6980ae1a7)

**Comment by milvus-milvus** [comment]
Praczko Adrianna_Praczko Adrianna.zip
<https://drive.google.com/file/d/1MhZ-jWc6GZJ4vlwtzHp5X3N7aGWEtcRz/view?usp=drive_web>
Hello Andrey!
Thank you very much for replying!
I will provide more details right away.
I use OpenSim to calculate normalized muscle-tendon length during gait
cycle. I used the Arnoldetal2010_2Legs_Default_v2.1.osim model instead of
yours because yours doesn't have muscles. I changed marker placement and
all the names before I used it in simulation. I actually did this
simulation for a few patients and it worked, so I have no idea what the
problem is. I am sending you my customized model as well as my patient
data. In my patient file there are files .mot and .trc acquired during one
static and two dynamic trials. From both trials I chose only one step, one
for left and one for right leg. After applying inverse kinematics the model
is going in the direction of a real trial but like "from side to side". If
I can answer any other question please let me know.

Best regards
Urszula Kania


sob., 17 cze 2023 o 11:44 AndreyAkse ***@***.***> napisał(a):

**Comment by AndreyAkse** [comment]
Hello Ursula, 

I was looking at your data but there were no your modified model.
I also want to mention that there are muscles in the model examples that are coming with paf opensim example. If you use gait2392_simbody_IOR.osim model then you can go to **Forces** and there will be **Muscles** and then **all**. If you select **all** and right click mouse press **display** and **Show**.
They were just hidden but I used recently IOR model and few comparisons in OpenSim to calculate muscle forces, Knee extension and flexion forces.


Best wishes, 

Andrey

<img width="634" alt="image" src="https://github.com/qualisys/paf-opensim-example/assets/120633101/f39ee284-b8d6-45a8-9273-b7de450df054">

<img width="708" alt="image" src="https://github.com/qualisys/paf-opensim-example/assets/120633101/4379e96a-deff-4f4d-90c5-5521f3416406">
